ENV_PLEX_TOKEN = "PLEX_TOKEN"
ENV_PLEX_HOST = "PLEX_HOST"
ENV_PLEX_WEBHOOK_ENDPOINT = "PLEX_WEBOOK_ENDPOINT"

ENV_RADARR_API_KEY = "RADARR_API_KEY"
ENV_RADARR_HOST = "RADARR_HOST"

ENV_SONARR_API_KEY = "SONARR_API_KEY"
ENV_SONARR_HOST = "SONARR_HOST"

ENV_SAB_API_KEY = "SAB_API_KEY"
ENV_SAB_HOST = "SAB_HOST"